### ISSUE TITLE
Possible Python wrapper for face alignment

### ISSUE THREAD

**Issue by DonaldTsang** [ManuBN786/Face-Alignment-using-Dlib-OpenCV#1]
Is it possible to add a Python wrapper that extracts and aligns the face(s) in an image?
- Input: Image file path of the image with faces
- Output: Image file path(s) of new files generated by old files

**Comment by ManuBN786** [comment]
Please check this one also : https://github.com/ManuBN786/FaceAlignCorrect

I will do it in course of time
