### ISSUE TITLE
Convert to gray twice?

### ISSUE THREAD

**Issue by jmtaijiquan** [ManuBN786/Face-Alignment-using-Dlib-OpenCV#3]
The code below is duplicated:

    //converts original image to gray scale and stores it in "gray".
    cvtColor(image,gray,COLOR_BGR2GRAY);

    //resize the gray scale image for speeding the face detection.
    cv::resize(gray,resized,Size(),scale,scale);

    //converts original image to gray scale and stores it in "gray".
    cvtColor(image,gray,COLOR_BGR2GRAY);

    //resize the gray scale image for speeding the face detection.
    cv::resize(gray,resized,Size(),scale,scale);

**Comment by ManuBN786** [comment]
Oh Its by mistake.
No Need to convert twice.
